
export const SEARCH_TRACK = 'SEARCH_TRACK';
export const SEARCH_TRACK_QUERY = 'SEARCH_TRACK_QUERY';
export const SEARCH_TRACK_QUEUE = 'SEARCH_TRACK_QUEUE';

export const FILTER_TRACKS_BY = 'FILTER_BY';
export const ORDER_TRACKS_BY = 'ORDER_TRACKS_BY';

export const TRACKS_QUERY_ERROR = 'TRACKS_QUERY_ERROR';
export const TRACKS_QUERY_LOADING = 'TRACKS_QUERY_LOADING';
export const TRACKS_QUERY_SUCCESS = 'TRACKS_QUERY_SUCCESS';
